: >= 2DUP = ROT > OR ;
: <= 2DUP = ROT < OR ;
: 0= 0 = ;
: 0<> 0 <> ;
: 0< 0 < ;
: 0> 0 > ;
: 0<= 0 <= ;
: 0>= 0 >= ;

: NEGATE 0 SWAP - ;
: TRUE 1 ;
: FALSE 0 ;

: IF IMMEDIATE ' 0BRANCH , HERE @ 0 , ;
: THEN IMMEDIATE DUP HERE @ SWAP - SWAP ! ;
: ELSE IMMEDIATE ' BRANCH , HERE @ 0 , SWAP DUP HERE @ SWAP - SWAP ! ;

: [COMPILE] IMMEDIATE WORD FIND >CFA , ;
: RECURSE IMMEDIATE LATEST @ >CFA , ;

: DOIT TRUE IF 65 EMIT 10 EMIT THEN 66 EMIT 10 EMIT ;
: EMITEVEN DUP 2 MOD 0= IF EMIT 10 EMIT ELSE 33 EMIT 10 EMIT DROP THEN ;
: EMITANY DUP 0<> IF EMIT 10 EMIT THEN ;

: FAC DUP 0= IF DROP 1 ELSE DUP 1- RECURSE * THEN ;
