name:                hskahn
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/derrickturk/hskahn#readme
license:             GPL-3
author:              Derrick W. Turk
maintainer:          dwt@terminusdatascience.com
copyright:           dwt | terminus data science, LLC
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - containers
  - megaparsec
  - mtl
  - text

library:
    source-dirs:      src

executables:
  hskahn:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
      - -O2
      - -Wall
    dependencies:
      - hskahn
