name:                hspassphrase
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/derrickturk/hspassphrase#readme
license:             GPL-3
author:              Derrick W. Turk
maintainer:          dwt@terminusdatascience.com
copyright:           dwt | terminus data science, LLC
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text

executables:
  hspassphrase:
    source-dirs:      src
    main:             Main.hs
  hspassphrase2:
    source-dirs:      src2
    main:             Main.hs
