name:                hstower
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/derrickturk/hstower#readme
license:             GPL-3
author:              Derrick W. Turk
maintainer:          dwt@terminusdatascience.com
copyright:           dwt | terminus data science, LLC
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text
  - megaparsec

executables:
  hstower:
    source-dirs:      src
    main:             Main.hs
  hstower2:
    source-dirs:      src2
    main:             Main.hs
