name:                hsclaim
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/derrickturk/hsclaim#readme
license:             GPL-3
author:              Derrick W. Turk
maintainer:          dwt@terminusdatascience.com
copyright:           dwt | terminus data science, LLC
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - text
  - vector

library:
    source-dirs:      src

executables:
  hsclaim:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
      - -O2
      - -Wall
    dependencies:
      - hsclaim
  hsclaim2:
    source-dirs:      app2
    main:             Main.hs
    ghc-options:
      - -O2
      - -Wall
    dependencies:
      - hsclaim
  hsclaim_fast:
    source-dirs:      app3
    main:             Main.hs
    ghc-options:
      - -O2
      - -Wall
    dependencies:
      - hsclaim
